[[constraint]]
  name = "github.com/masaruhoshi/uptimerobot-go.v2"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.6"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true
